# DX 704 Week 1 Project

This week's project will build a portfolio risk and return model, and make investing recommendations for hypothetical clients.
You will collect historical data, estimate returns and risks, construct efficient frontier portfolios, and sanity check the certainty of the maximum return portfolio.

The full project description and a template notebook are available on GitHub at the following link.

https://github.com/bu-cds-dx704/dx704-project-01

Feel free to use optimization tools or libraries (such as CVXOPT or scipy.optimize) to perform any calculations required for this mini project.

### Example Code

You may find it helpful to refer to these GitHub repositories of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples
* https://github.com/bu-cds-omds/dx603-examples
* https://github.com/bu-cds-omds/dx704-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Part 1: Collect Data

Collect historical monthly price data for the last 24 months covering 6 different stocks.
The data should cover 24 consecutive months including the last month that ended before this week's material was released on Blackboard.
To be clear, if a month ends between the Blackboard release and submitting your project, you do not need to add that month.

The six different stocks must include AAPL, SPY and TSLA.
At least one of the remaining 3 tickers must start with the same letter as your last name (e.g. professor Considine could use COIN).
This is to encourage diversity in what stocks you analyze; if you discuss this project with classmates, please make sure that you pick different tickers to differentiate your work.
Do not pick stocks with fewer than 24 consecutive months of price data.

In [41]:
# YOUR CHANGES HERE

# Adjusted closing price data from Yahoo Finance
# https://finance.yahoo.com/quote/AAPL/history/?frequency=1mo&period1=1756771200&period2=1788307200
# https://finance.yahoo.com/quote/%5EGSPC/history/?frequency=1mo&period1=1756771200&period2=1788307200
# https://finance.yahoo.com/quote/TSLA/history/?frequency=1mo&period1=1756771200&period2=1788307200
# https://finance.yahoo.com/quote/EURUSD%3DX/history/?period1=1756771200&period2=1788307200
# https://finance.yahoo.com/quote/META/history/?frequency=1mo&period1=1756771200&period2=1788307200
# https://finance.yahoo.com/quote/SPOT/history/?frequency=1mo&period1=1756771200&period2=1788307200

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Historical prices (Adj Close)
aapl_prices = [
    253.69, 269.37, 278.09, 271.12, 258.78, 263.71, 253.34, 270.87, 311.79, 289.11, 308.64, 316.85, # 319.97
]

gspc_prices = [
    6688.46, 6840.20, 6849.09, 6845.50, 6939.03, 6878.88, 6528.52, 7209.01, 7580.06, 7499.36, 7489.72, 7686.14, # 7718.60
]

tsla_prices = [
    444.72, 456.56, 430.17, 449.72, 430.41, 402.51, 371.75, 381.63, 435.79, 420.60, 311.21, 367.95, # 354.08
]

eurusd_prices = [
    1.1731, 1.1572, 1.1597, 1.1747, 1.1855, 1.1803, 1.1460, 1.1685, 1.1660, 1.1422, 1.1524, 1.1589, # 1.1621
]

meta_prices = [
    732.47, 646.67, 646.27, 658.91, 715.22, 647.03, 571.60, 611.34, 631.92, 563.29, 556.71, 572.34, # 616.77
]

spot_prices = [
    698.00, 655.32, 598.87, 580.71, 500.35, 514.94, 484.91, 446.55, 497.68, 459.13, 499.94, 543.62, # 542.43
]

# Create a Pandas DataFrame
historical_prices = pd.DataFrame({
    "Date": pd.date_range(start="2025-09-01", end="2026-09-01", freq="ME", inclusive="both"),
    "AAPL": aapl_prices,
    "GSPC": gspc_prices,
    "TSLA": tsla_prices,
    "EURUSD": eurusd_prices,
    "META": meta_prices,
    "SPOT": spot_prices
})

historical_prices.set_index("Date", inplace=True)
historical_prices

              AAPL     GSPC    TSLA  EURUSD    META    SPOT
Date
2025-09-30  253.69  6688.46  444.72  1.1731  732.47  698.00
2025-10-31  269.37  6840.20  456.56  1.1572  646.67  655.32
2025-11-30  278.09  6849.09  430.17  1.1597  646.27  598.87
2025-12-31  271.12  6845.50  449.72  1.1747  658.91  580.71
2026-01-31  258.78  6939.03  430.41  1.1855  715.22  500.35
2026-02-28  263.71  6878.88  402.51  1.1803  647.03  514.94
2026-03-31  253.34  6528.52  371.75  1.1460  571.60  484.91
2026-04-30  270.87  7209.01  381.63  1.1685  611.34  446.55
2026-05-31  311.79  7580.06  435.79  1.1660  631.92  497.68
2026-06-30  289.11  7499.36  420.60  1.1422  563.29  459.13
2026-07-31  308.64  7489.72  311.21  1.1524  556.71  499.94
2026-08-31  316.85  7686.14  367.95  1.1589  572.34  543.62

Save the data as a TSV file named "historical_prices.tsv" and include a header row with the column names "date" and the 6 stock ticker symbols.
The date should be the last trading day of the month, so it may not be the last day of the month.
For example, the last trading day of November 2024 was 2024-11-29.
The remaining columns should contain the adjusted closing prices of the corresponding stock tickers on that day.

In [42]:
# YOUR CHANGES HERE

# Save historical prices data as TSV file named "historical_prices.tsv"
historical_prices.to_csv("historical_prices.tsv", sep="\t")

Submit "historical_prices.tsv" in Gradescope.

## Part 2: Calculate Historical Asset Returns

Calculate the historical asset returns based on the price data that you previously collected.

In [43]:
# YOUR CHANGES HERE

# Calculate historical asset returns
historical_returns = historical_prices.pct_change().dropna()
historical_returns

# Plot historical asset returns
# historical_returns.plot()

                AAPL      GSPC      TSLA    EURUSD      META      SPOT
Date
2025-10-31  0.061808  0.022687  0.026623 -0.013554 -0.117138 -0.061146
2025-11-30  0.032372  0.001300 -0.057802  0.002160 -0.000619 -0.086141
2025-12-31 -0.025064 -0.000524  0.045447  0.012934  0.019558 -0.030324
2026-01-31 -0.045515  0.013663 -0.042938  0.009194  0.085459 -0.138382
2026-02-28  0.019051 -0.008668 -0.064822 -0.004386 -0.095341  0.029160
2026-03-31 -0.039323 -0.050933 -0.076420 -0.029060 -0.116579 -0.058317
2026-04-30  0.069196  0.104233  0.026577  0.019634  0.069524 -0.079107
2026-05-31  0.151069  0.051470  0.141918 -0.002139  0.033664  0.114500
2026-06-30 -0.072741 -0.010646 -0.034856 -0.020412 -0.108606 -0.077459
2026-07-31  0.067552 -0.001285 -0.260081  0.008930 -0.011681  0.088886
2026-08-31  0.026601  0.026225  0.182321  0.005640  0.028076  0.087370

Save the data as a TSV file named "historical_returns.tsv" and include a header row with the column names "date" and the 6 stock ticker symbols.
Each row should have the date at the end of the month and the corresponding *relative* price changes.
For example, if the previous price was \$100 and the new price is \$110, the return value should be 0.10.
There should only be 23 rows of data in this file, since they are computed as the differences of 24 prices.

In [44]:
# YOUR CHANGES HERE

# Save historical asset returns as TSV file named "historical _returns.tsv"
historical_returns.to_csv("historical_returns.tsv", sep="\t")

Submit "historical_returns.tsv" in Gradescope.

## Part 3: Estimate Returns

Estimate the expected returns for each asset using the previously calculated return data.
Just compute the average (mean) return for each asset over your data set; do not use other estimators that have been mentioned.
This will serve as your estimate of expected return for each asset.

In [45]:
# YOUR CHANGES HERE

# Estimate expected returns
expected_returns = historical_returns.mean()
expected_returns

AAPL      0.022273
GSPC      0.013411
TSLA     -0.010367
EURUSD   -0.001005
META     -0.019426
SPOT     -0.019178
dtype: float64

Save the estimated returns in a TSV file named "estimated_returns.tsv" and include a header row with the column names "asset" and "estimated_return".

In [46]:
# YOUR CHANGES HERE

# Save expected returns as TSV file named "expected_returns.tsv"
expected_returns.to_csv("expected_returns.tsv", sep="\t")

Submit "estimated_returns.tsv" in Gradescope.

## Part 4: Estimate Risk

Estimate the covariance matrix for the asset returns to understand how the assets move together.

In [47]:
# YOUR CHANGES HERE

# Estimate covariance matrix for asset returns
covariance_matrix = historical_returns.cov()
covariance_matrix

            AAPL      GSPC      TSLA    EURUSD      META      SPOT
AAPL    0.004219  0.001576  0.001799  0.000307  0.001364  0.003382
GSPC    0.001576  0.001571  0.002146  0.000377  0.001902  0.000282
TSLA    0.001799  0.002146  0.013976  0.000173  0.002558  0.001795
EURUSD  0.000307  0.000377  0.000173  0.000221  0.000978  0.000140
META    0.001364  0.001902  0.002558  0.000978  0.005862  0.000290
SPOT    0.003382  0.000282  0.001795  0.000140  0.000290  0.007234

Save the estimated covariances to a TSV file named "estimated_covariance.tsv".
The header row should have a blank column name followed by the names of the assets.
Each data row should start with the name of an asset for that row, and be followed by the individual covariances corresponding to that row and column's assets.
(This is the format of pandas's `to_csv` method with `sep="\t"` when used on a covariance matrix as computed in the examples.)

In [48]:
# YOUR CHANGES HERE

# Save covariance matrix as TSV file named "estimated_covariance.tsv"
covariance_matrix.to_csv("estimated_covariance.tsv", sep="\t")

Submit "estimated_covariance.tsv" in Gradescope.

## Part 5: Construct the Maximum Return Portfolio

Compute the maximum return portfolio based on your previously estimated risks and returns.

In [49]:
# YOUR CHANGES HERE

# Construct maximum return portfolio

Save the maximum return portfolio in a TSV file named "maximum_return.tsv".
The header row should have two columns, "asset" and "allocation".
The allocation values should sum up to one.

In [50]:
# YOUR CHANGES HERE

...

Ellipsis

Submit "maximum_return.tsv" in Gradescope.

## Part 6: Construct the Minimum Risk Portfolio

Compute the minimum risk portfolio based on your previously estimated risks.

In [51]:
# YOUR CHANGES HERE

...

Ellipsis

Save the minimum risk portfolio in a TSV file named "minimum_risk.tsv".
The header row should have two columns, "asset" and "allocation".
The allocation values should sum up to one.

In [52]:
# YOUR CHANGES HERE

...

Ellipsis

Submit "minimum_risk.tsv" in Gradescope.

## Part 7: Build Efficient Frontier Portfolios

Compute 101 portfolios along the mean-variance efficient frontier with evenly spaced estimated returns.
The first portfolio should be the minimum risk portfolio from part 4, and the last portfolio should be the maximum return portfolio from part 3.
The estimated return of each portfolio should be higher than the previous by one percent of the difference between the first and last portfolios.
That is, the estimated return of the portfolios should be similar to `np.linspace(min_risk_return, max_return, 101)`.

In [53]:
# YOUR CHANGES HERE

...

Ellipsis

Save the portfolios in a TSV file named "efficient_frontier.tsv".
The header row should have columns "index", "return", "risk", and all the asset tickers.
Each data row should have the portfolio index (0-100), the estimated return of the portfolio, the estimated standard deviation (not variance) of the portfolio, and all the asset allocations (which should sum to one).

In [54]:
# YOUR CHANGES HERE

...

Ellipsis

Submit "efficient_frontier.tsv" in Gradescope.

## Part 8: Check Maximum Return Portfolio Stability

Check the stability of the maximum return portfolio by resampling the estimated risk/return model.

Repeat 1000 times -
1. Use `np.random.multivariate_normal` to generate 23 return samples using your previously estimated risks and returns.
2. Estimate the return of each asset using that resampled return history.
3. Check which asset had the highest return in those resampled estimates.

This procedure is a reduced and simplified version of the Michaud resampled efficient frontier procedure that takes uncertainty in the risk model into account.

In [55]:
# YOUR CHANGES HERE

...

Ellipsis

Save a file "max_return_probabilities.tsv" with the distribution of highest return assets.
The header row should have columns "asset" and "probability".
There should be a data row for each asset and its sample probability of having the highest return based on those 1000 resampled estimates.

In [56]:
# YOUR CHANGES HERE

...

Ellipsis

Submit "max_return_probabilities.tsv" in Gradescope.

## Part 9: Acknowledgments

Make a file "acknowledgments.txt" documenting any outside sources or help on this project.
If you discussed this assignment with anyone, please acknowledge them here.
If you used any libraries not mentioned in this module's content, please list them with a brief explanation what you used them for.
If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the generative AI policy.
If no acknowledgments are appropriate, just write none in the file.

Submit "acknowledgments.txt" in Gradescope.

## Part 10: Code

Please submit a Jupyter notebook that can reproduce all your calculations and recreate the previously submitted files.
You do not need to provide code for data collection if you did that by manually.

Submit "project.ipynb" in Gradescope.