# DX 704 Week 1 Project

This week's project will build a portfolio risk and return model, and make investing recommendations for hypothetical clients.
You will collect historical data, estimate returns and risks, construct efficient frontier portfolios, and sanity check the certainty of the maximum return portfolio.

The full project description and a template notebook are available on GitHub at the following link.

https://github.com/bu-cds-dx704/dx704-project-01

Feel free to use optimization tools or libraries (such as CVXOPT or scipy.optimize) to perform any calculations required for this mini project.

### Example Code

You may find it helpful to refer to these GitHub repositories of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples
* https://github.com/bu-cds-omds/dx603-examples
* https://github.com/bu-cds-omds/dx704-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Part 1: Collect Data

Collect historical monthly price data for the last 24 months covering 6 different stocks.
The data should cover 24 consecutive months including the last month that ended before this week's material was released on Blackboard.
To be clear, if a month ends between the Blackboard release and submitting your project, you do not need to add that month.

The six different stocks must include AAPL, SPY and TSLA.
At least one of the remaining 3 tickers must start with the same letter as your last name (e.g. professor Considine could use COIN).
This is to encourage diversity in what stocks you analyze; if you discuss this project with classmates, please make sure that you pick different tickers to differentiate your work.
Do not pick stocks with fewer than 24 consecutive months of price data.

In [1]:
# YOUR CHANGES HERE

# Adjusted closing price data from Yahoo Finance
# https://finance.yahoo.com/quote/AAPL/history/?frequency=1mo&period1=1756771200&period2=1788307200
# https://finance.yahoo.com/quote/%5EGSPC/history/?frequency=1mo&period1=1756771200&period2=1788307200
# https://finance.yahoo.com/quote/TSLA/history/?frequency=1mo&period1=1756771200&period2=1788307200
# https://finance.yahoo.com/quote/EURUSD%3DX/history/?period1=1756771200&period2=1788307200
# https://finance.yahoo.com/quote/META/history/?frequency=1mo&period1=1756771200&period2=1788307200
# https://finance.yahoo.com/quote/SPOT/history/?frequency=1mo&period1=1756771200&period2=1788307200

%pip install numpy
%pip install pandas
%pip install matplotlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Historical prices (Adj Close)
aapl_prices = [
    231.07, 224.04, 235.62, 248.62, 234.30, 240.36, 220.77, 211.20, 199.88, 204.18, 206.57, 231.29, 253.69, 269.37, 278.09, 271.12, 258.78, 263.71, 253.34, 270.87, 311.79, 289.11, 308.64, 316.85
]

spy_prices = [
    5762.48, 5705.45, 6032.38, 5881.63, 6040.53, 5954.50, 5611.85, 5569.06, 5911.69, 6204.95, 6339.39, 6460.26, 6688.46, 6840.20, 6849.09, 6845.50, 6939.03, 6878.88, 6528.52, 7209.01, 7580.06, 7499.36, 7489.72, 7686.14
]

tsla_prices = [
    261.63, 249.85, 345.16, 403.84, 404.60, 292.98, 259.16, 282.16, 346.46, 317.66, 308.27, 333.87, 444.72, 456.56, 430.17, 449.72, 430.41, 402.51, 371.75, 381.63, 435.79, 420.60, 311.21, 367.95
]

eurusd_prices = [
    1.0859, 1.0581, 1.0406, 1.0397, 1.0395, 1.0824, 1.1389, 1.1351, 1.1727, 1.1429, 1.1686, 1.1731, 1.1572, 1.1597, 1.1747, 1.1855, 1.1803, 1.1460, 1.1685, 1.1660, 1.1422, 1.1524, 1.1589, 1.1621
]

meta_prices = [
    567.17, 564.33, 571.03, 582.63, 685.79, 664.91, 574.04, 546.79, 644.88, 735.68, 770.91, 736.29, 732.47, 646.67, 646.27, 658.91, 715.22, 647.03, 571.60, 611.34, 631.92, 563.29, 556.71, 572.34 
]

spot_prices = [
    368.53, 385.10, 476.96, 447.38, 548.55, 608.01, 550.03, 613.98, 665.14, 767.34, 626.54, 681.88, 698.00, 655.32, 598.87, 580.71, 500.35, 514.94, 484.91, 446.55, 497.68, 459.13, 499.94, 543.62
]

# Create a Pandas DataFrame
historical_prices = pd.DataFrame({
    "Date": pd.date_range(start="2024-09-01", end="2026-09-01", freq="ME", inclusive="both"),
    "AAPL": aapl_prices,
    "SPY": spy_prices,
    "TSLA": tsla_prices,
    "EURUSD": eurusd_prices,
    "META": meta_prices,
    "SPOT": spot_prices
})

historical_prices.set_index("Date", inplace=True)
historical_prices

Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (2.5.3)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.14/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/codespace/.local/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

              AAPL      SPY    TSLA  EURUSD    META    SPOT
Date
2024-09-30  231.07  5762.48  261.63  1.0859  567.17  368.53
2024-10-31  224.04  5705.45  249.85  1.0581  564.33  385.10
2024-11-30  235.62  6032.38  345.16  1.0406  571.03  476.96
2024-12-31  248.62  5881.63  403.84  1.0397  582.63  447.38
2025-01-31  234.30  6040.53  404.60  1.0395  685.79  548.55
2025-02-28  240.36  5954.50  292.98  1.0824  664.91  608.01
2025-03-31  220.77  5611.85  259.16  1.1389  574.04  550.03
2025-04-30  211.20  5569.06  282.16  1.1351  546.79  613.98
2025-05-31  199.88  5911.69  346.46  1.1727  644.88  665.14
2025-06-30  204.18  6204.95  317.66  1.1429  735.68  767.34
2025-07-31  206.57  6339.39  308.27  1.1686  770.91  626.54
2025-08-31  231.29  6460.26  333.87  1.1731  736.29  681.88
2025-09-30  253.69  6688.46  444.72  1.1572  732.47  698.00
2025-10-31  269.37  6840.20  456.56  1.1597  646.67  655.32
2025-11-30  278.09  6849.09  430.17  1.1747  646.27  598.87
2025-12-31  271.12  6845.50  449.72  1.1855  658.91  580.71
2026-01-31  258.78  6939.03  430.41  1.1803  715.22  500.35
2026-02-28  263.71  6878.88  402.51  1.1460  647.03  514.94
2026-03-31  253.34  6528.52  371.75  1.1685  571.60  484.91
2026-04-30  270.87  7209.01  381.63  1.1660  611.34  446.55
2026-05-31  311.79  7580.06  435.79  1.1422  631.92  497.68
2026-06-30  289.11  7499.36  420.60  1.1524  563.29  459.13
2026-07-31  308.64  7489.72  311.21  1.1589  556.71  499.94
2026-08-31  316.85  7686.14  367.95  1.1621  572.34  543.62

Save the data as a TSV file named "historical_prices.tsv" and include a header row with the column names "date" and the 6 stock ticker symbols.
The date should be the last trading day of the month, so it may not be the last day of the month.
For example, the last trading day of November 2024 was 2024-11-29.
The remaining columns should contain the adjusted closing prices of the corresponding stock tickers on that day.

In [2]:
# YOUR CHANGES HERE

# Save historical prices data as TSV file named "historical_prices.tsv"
historical_prices.to_csv("historical_prices.tsv", sep="\t")

Submit "historical_prices.tsv" in Gradescope.

## Part 2: Calculate Historical Asset Returns

Calculate the historical asset returns based on the price data that you previously collected.

In [3]:
# YOUR CHANGES HERE

# Calculate historical asset returns
historical_returns = historical_prices.pct_change().dropna()
historical_returns

# Plot historical asset returns
# historical_returns.plot()

                AAPL       SPY      TSLA    EURUSD      META      SPOT
Date
2024-10-31 -0.030424 -0.009897 -0.045025 -0.025601 -0.005007  0.044962
2024-11-30  0.051687  0.057301  0.381469 -0.016539  0.011872  0.238535
2024-12-31  0.055174 -0.024990  0.170008 -0.000865  0.020314 -0.062018
2025-01-31 -0.057598  0.027016  0.001882 -0.000192  0.177059  0.226139
2025-02-28  0.025864 -0.014242 -0.275877  0.041270 -0.030447  0.108395
2025-03-31 -0.081503 -0.057545 -0.115435  0.052199 -0.136665 -0.095360
2025-04-30 -0.043348 -0.007625  0.088748 -0.003337 -0.047471  0.116266
2025-05-31 -0.053598  0.061524  0.227885  0.033125  0.179392  0.083325
2025-06-30  0.021513  0.049607 -0.083126 -0.025411  0.140801  0.153652
2025-07-31  0.011705  0.021667 -0.029560  0.022487  0.047888 -0.183491
2025-08-31  0.119669  0.019067  0.083044  0.003851 -0.044908  0.088326
2025-09-30  0.096848  0.035324  0.332015 -0.013554 -0.005188  0.023641
2025-10-31  0.061808  0.022687  0.026623  0.002160 -0.117138 -0.061146
2025-11-30  0.032372  0.001300 -0.057802  0.012934 -0.000619 -0.086141
2025-12-31 -0.025064 -0.000524  0.045447  0.009194  0.019558 -0.030324
2026-01-31 -0.045515  0.013663 -0.042938 -0.004386  0.085459 -0.138382
2026-02-28  0.019051 -0.008668 -0.064822 -0.029060 -0.095341  0.029160
2026-03-31 -0.039323 -0.050933 -0.076420  0.019634 -0.116579 -0.058317
2026-04-30  0.069196  0.104233  0.026577 -0.002139  0.069524 -0.079107
2026-05-31  0.151069  0.051470  0.141918 -0.020412  0.033664  0.114500
2026-06-30 -0.072741 -0.010646 -0.034856  0.008930 -0.108606 -0.077459
2026-07-31  0.067552 -0.001285 -0.260081  0.005640 -0.011681  0.088886
2026-08-31  0.026601  0.026225  0.182321  0.002761  0.028076  0.087370

Save the data as a TSV file named "historical_returns.tsv" and include a header row with the column names "date" and the 6 stock ticker symbols.
Each row should have the date at the end of the month and the corresponding *relative* price changes.
For example, if the previous price was \$100 and the new price is \$110, the return value should be 0.10.
There should only be 23 rows of data in this file, since they are computed as the differences of 24 prices.

In [4]:
# YOUR CHANGES HERE

# Save historical asset returns as TSV file named "historical_returns.tsv"
historical_returns.to_csv("historical_returns.tsv", sep="\t")

Submit "historical_returns.tsv" in Gradescope.

## Part 3: Estimate Returns

Estimate the expected returns for each asset using the previously calculated return data.
Just compute the average (mean) return for each asset over your data set; do not use other estimators that have been mentioned.
This will serve as your estimate of expected return for each asset.

In [5]:
# YOUR CHANGES HERE

# Estimate expected returns
expected_returns = historical_returns.mean()
# expected_returns

# Construct expected returns DataFrame
maximum_returns_df = pd.DataFrame({
    "Asset" : expected_returns.index,
    "Mean" : historical_returns.mean()
})

maximum_returns_df.set_index("Asset", inplace=True)
maximum_returns_df

            Mean
Asset
AAPL    0.015695
SPY     0.013249
TSLA    0.027043
EURUSD  0.003160
META    0.004085
SPOT    0.023105

Save the estimated returns in a TSV file named "estimated_returns.tsv" and include a header row with the column names "asset" and "estimated_return".

In [6]:
# YOUR CHANGES HERE

# Save expected returns as TSV file named "estimated_returns.tsv"
expected_returns.to_csv("estimated_returns.tsv", sep="\t")

Submit "estimated_returns.tsv" in Gradescope.

## Part 4: Estimate Risk

Estimate the covariance matrix for the asset returns to understand how the assets move together.

In [7]:
# YOUR CHANGES HERE

# Estimate covariance matrix for asset returns
covariance_matrix = historical_returns.cov()
covariance_matrix

            AAPL       SPY      TSLA    EURUSD      META      SPOT
AAPL    0.004014  0.001044  0.002828 -0.000520 -0.000018  0.001381
SPY     0.001044  0.001377  0.002830 -0.000291  0.002118  0.001281
TSLA    0.002828  0.002830  0.026124 -0.001095  0.003458  0.004676
EURUSD -0.000520 -0.000291 -0.001095  0.000438 -0.000322 -0.000815
META   -0.000018  0.002118  0.003458 -0.000322  0.007842  0.003370
SPOT    0.001381  0.001281  0.004676 -0.000815  0.003370  0.012952

Save the estimated covariances to a TSV file named "estimated_covariance.tsv".
The header row should have a blank column name followed by the names of the assets.
Each data row should start with the name of an asset for that row, and be followed by the individual covariances corresponding to that row and column's assets.
(This is the format of pandas's `to_csv` method with `sep="\t"` when used on a covariance matrix as computed in the examples.)

In [8]:
# YOUR CHANGES HERE

# Save covariance matrix as TSV file named "estimated_covariance.tsv"
covariance_matrix.to_csv("estimated_covariance.tsv", sep="\t")

Submit "estimated_covariance.tsv" in Gradescope.

## Part 5: Construct the Maximum Return Portfolio

Compute the maximum return portfolio based on your previously estimated risks and returns.

In [9]:
# YOUR CHANGES HERE

%pip install cvxpy
import cvxpy as cp

# Compute maximum return
n = len(expected_returns)
x = cp.Variable(n)

objective = cp.Maximize(expected_returns.to_numpy().reshape(1, -1) @ x)
# objective

prob = cp.Problem(objective, [0 <= x, cp.sum(x) == 1])

estimated_return_P = prob.solve()
# estimated_return_P

x.value.round(2)

# Construct maximum return portfolio
maximum_return_portfolio = pd.DataFrame({
    "Asset" : expected_returns.index,
    "Allocation" : x.value.round(2),
})

maximum_return_portfolio.set_index("Asset", inplace=True)
maximum_return_portfolio

Requirement already satisfied: cvxpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (1.9.2)
Requirement already satisfied: osqp>=1.0.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cvxpy) (1.1.3)
Requirement already satisfied: clarabel>=0.5.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cvxpy) (0.11.1)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cvxpy) (3.3.1)
Requirement already satisfied: numpy>=2.0.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cvxpy) (2.5.3)
Requirement already satisfied: scipy>=1.13.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cvxpy) (1.18.1)
Requirement already satisfied: highspy>=1.14.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cvxpy) (1.15.1)
Requirement already satisfied: qdldl>=0.1.7.post0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cvxpy) (0.1.9.post1)
Requirement already satisfied: sparsediffpy<0.4.0,>=0.3.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cvxpy) (0.3.0)
Requirement already satisfied: cffi in /home/codespace/.local/lib/python3.14/site-packages (from clarabel>=0.5.0->cvxpy) (2.1.1)
Requirement already satisfied: jinja2 in /home/codespace/.local/lib/python3.14/site-packages (from osqp>=1.0.0->cvxpy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/python/3.14.2/lib/python3.14/site-packages (from osqp>=1.0.0->cvxpy) (84.0.0)
Requirement already satisfied: joblib in /usr/local/python/3.14.2/lib/python3.14/site-packages (from osqp>=1.0.0->cvxpy) (1.6.0)
Requirement already satisfied: pycparser in /home/codespace/.local/lib/python3.14/site-packages (from cffi->clarabel>=0.5.0->cvxpy) (3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.local/lib/python3.14/site-packages (from jinja2->osqp>=1.0.0->cvxpy) (3.0.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from joblib->osqp>=1.0.0->cvxpy) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

        Allocation
Asset
AAPL           0.0
SPY            0.0
TSLA           1.0
EURUSD         0.0
META           0.0
SPOT           0.0

Save the maximum return portfolio in a TSV file named "maximum_return.tsv".
The header row should have two columns, "asset" and "allocation".
The allocation values should sum up to one.

In [10]:
# YOUR CHANGES HERE

# Save maximum return portfolio as TSV file named "maximum_return.tsv"
maximum_return_portfolio.to_csv("maximum_return.tsv", sep="\t")

Submit "maximum_return.tsv" in Gradescope.

## Part 6: Construct the Minimum Risk Portfolio

Compute the minimum risk portfolio based on your previously estimated risks.

In [11]:
# YOUR CHANGES HERE

# Compute minimum return
n = len(expected_returns)
x_minimum_risk = cp.Variable(n)

objective_minimum_risk = cp.Minimize(x_minimum_risk.T @ covariance_matrix.to_numpy() @ x_minimum_risk)
# objective_minimum_risk

prob_minimum_risk = cp.Problem(objective_minimum_risk, [0 <= x_minimum_risk, cp.sum(x_minimum_risk) == 1])

covariance_minimum_risk = prob_minimum_risk.solve()
# covariance_minimum_risk

x_minimum_risk.value.round(2)

# Construct minimum risk portfolio
minimum_risk_portfolio = pd.DataFrame({
    "Asset" : expected_returns.index,
    "Allocation" : x_minimum_risk.value.round(2),
})

# minimum_risk_portfolio.set_index("Asset", inplace=True)
minimum_risk_portfolio

    Asset  Allocation
0    AAPL        0.07
1     SPY        0.19
2    TSLA        0.00
3  EURUSD        0.70
4    META        0.00
5    SPOT        0.03

Save the minimum risk portfolio in a TSV file named "minimum_risk.tsv".
The header row should have two columns, "asset" and "allocation".
The allocation values should sum up to one.

In [12]:
# YOUR CHANGES HERE

# Save minimum risk portfolio as TSV file named "minimum_risk.tsv"
minimum_risk_portfolio.to_csv("minimum_risk.tsv", sep="\t")

Submit "minimum_risk.tsv" in Gradescope.

## Part 7: Build Efficient Frontier Portfolios

Compute 101 portfolios along the mean-variance efficient frontier with evenly spaced estimated returns.
The first portfolio should be the minimum risk portfolio from part 4, and the last portfolio should be the maximum return portfolio from part 3.
The estimated return of each portfolio should be higher than the previous by one percent of the difference between the first and last portfolios.
That is, the estimated return of the portfolios should be similar to `np.linspace(min_risk_return, max_return, 101)`.

In [16]:
# YOUR CHANGES HERE

# Compute Efficient Frontier Portfolios
estimated_return_minimum_risk = x_minimum_risk.value @ expected_returns
# estimated_return_minimum_risk
estimated_return_maximum_return = expected_returns.max()
# estimated_return_maximum_return


# 101 optimized portfolios
efficient_variances = []
efficient_returns = []
efficient_portfolios = []

for r in np.linspace(estimated_return_minimum_risk, estimated_return_maximum_return, 101):
    x_r = cp.Variable(n)

    prob_r = cp.Problem(cp.Minimize(x_r.T @ covariance_matrix.to_numpy() @ x_r), 
                        [0 <= x_r, cp.sum(x_r) == 1, expected_returns.to_numpy().reshape(1, -1) @ x_r == r])

    efficient_variances.append(prob_r.solve())
    efficient_returns.append(r)
    efficient_portfolios.append(x_r.value)

efficient_portfolios = np.asarray(efficient_portfolios).round(2)
# efficient_portfolios


# Construct DataFrame
efficient_portfolios_df = pd.DataFrame({
    "Index" : range(1, len(efficient_portfolios) + 1),
    "Return": efficient_returns,
    "Risk": np.sqrt(efficient_variances),
    "AAPL" : efficient_portfolios[:, 0],
     "SPY" : efficient_portfolios[:, 1],
     "TSLA" : efficient_portfolios[:, 2],
     "EURUSD" : efficient_portfolios[:, 3],
     "META" : efficient_portfolios[:, 4],
     "SPOT" : efficient_portfolios[:, 5]
})
efficient_portfolios_df

# VISUALS:
#
# 1. Portfolio Performance
# plt.plot(np.sqrt(covariance_matrix), expected_returns, label="Assets", linestyle="none", marker="o")
# plt.plot(np.sqrt(efficient_variances), efficient_returns, label="Efficient Frontier", linestyle="--")
#
# plt.legend()
# plt.xlabel("Risk (Standard Deviation)")
# plt.ylabel("Expected Return")
# plt.title("Mean-Variance Efficient Frontier and Individual Assets")
# plt.xlim(0)
# plt.ylim(0)
# plt.show()
#
# 2. Portfolio Composition Map
# plt.figure(figsize=(10, 5))
#
# bottom = np.zeros(efficient_portfolios.shape[0])
# for (i, a) in enumerate(historical_prices.columns):
#     plt.bar(x=efficient_returns,
#             height=efficient_portfolios[:, i],
#             bottom=bottom, 
#             label=a,
#             width=(efficient_returns[1]-efficient_returns[6]))
#     bottom += efficient_portfolios[:, i]
#
# plt.legend()
# plt.xlabel("Portfolio Expected Return")
# plt.xlim(estimated_return_minimum_risk, estimated_return_maximum_return)
# plt.ylabel("Portfolio Allocation")
# plt.title("Portfolio Composition Map of the Mean-Variance Efficient Frontier")
# plt.show()

     Index    Return      Risk  AAPL   SPY  TSLA  EURUSD  META  SPOT
0        1  0.006698  0.013585  0.07  0.19  0.00    0.70   0.0  0.03
1        2  0.006901  0.013615  0.08  0.20  0.00    0.68   0.0  0.03
2        3  0.007105  0.013705  0.08  0.21  0.00    0.67   0.0  0.04
3        4  0.007308  0.013854  0.08  0.22  0.00    0.65   0.0  0.04
4        5  0.007512  0.014059  0.09  0.23  0.00    0.64   0.0  0.04
..     ...       ...       ...   ...   ...   ...     ...   ...   ...
96      97  0.026229  0.136123  0.00  0.00  0.79    0.00   0.0  0.21
97      98  0.026433  0.142092 -0.00 -0.00  0.85   -0.00  -0.0  0.15
98      99  0.026636  0.148356 -0.00 -0.00  0.90   -0.00  -0.0  0.10
99     100  0.026840  0.154879 -0.00 -0.00  0.95   -0.00  -0.0  0.05
100    101  0.027043  0.161630 -0.00 -0.00  1.00   -0.00  -0.0 -0.00

[101 rows x 9 columns]

Save the portfolios in a TSV file named "efficient_frontier.tsv".
The header row should have columns "index", "return", "risk", and all the asset tickers.
Each data row should have the portfolio index (0-100), the estimated return of the portfolio, the estimated standard deviation (not variance) of the portfolio, and all the asset allocations (which should sum to one).

In [17]:
# YOUR CHANGES HERE

# Save Efficient Frontier Portfolios as TSV file named "efficient_frontier.tsv"
efficient_portfolios_df.to_csv("efficient_frontier.tsv", sep="\t")

Submit "efficient_frontier.tsv" in Gradescope.

## Part 8: Check Maximum Return Portfolio Stability

Check the stability of the maximum return portfolio by resampling the estimated risk/return model.

Repeat 1000 times -
1. Use `np.random.multivariate_normal` to generate 23 return samples using your previously estimated risks and returns.
2. Estimate the return of each asset using that resampled return history.
3. Check which asset had the highest return in those resampled estimates.

This procedure is a reduced and simplified version of the Michaud resampled efficient frontier procedure that takes uncertainty in the risk model into account.

In [18]:
# YOUR CHANGES HERE

# Check stability of maximum return portfolio by resampling the model
n_repeats = 1000
n_samples = 23

# Generate 23 return samples
assets = expected_returns.index
mean_vec = expected_returns.to_numpy()
cov_mat = covariance_matrix.to_numpy()

best_asset_counts = []

for n in range(n_repeats):
    simulated_returns = np.random.multivariate_normal(mean_vec, cov_mat, size=n_samples)

    # estimated return of each asset
    resampled_estimated_returns = simulated_returns.mean(axis=0)

    # asset with highest return in resampled estimates
    best_asset = assets[np.argmax(resampled_estimated_returns)]
    best_asset_counts.append(best_asset)

best_asset_counts = pd.DataFrame(best_asset_counts)

# Construct DataFrame
best_asset_counts_df = pd.DataFrame({
    'Asset': best_asset_counts[0].value_counts().index,
    'Probability': best_asset_counts[0].value_counts(normalize=True).values
})
best_asset_counts_df.set_index('Asset', inplace=True)
best_asset_counts_df

        Probability
Asset
TSLA          0.439
SPOT          0.314
AAPL          0.124
META          0.061
EURUSD        0.034
SPY           0.028

Save a file "max_return_probabilities.tsv" with the distribution of highest return assets.
The header row should have columns "asset" and "probability".
There should be a data row for each asset and its sample probability of having the highest return based on those 1000 resampled estimates.

In [20]:
# YOUR CHANGES HERE

# Save as TSV file named "max_return_probabilities.tsv"
best_asset_counts_df.to_csv("max_return_probabilities.tsv", sep="\t")

Submit "max_return_probabilities.tsv" in Gradescope.

## Part 9: Acknowledgments

Make a file "acknowledgments.txt" documenting any outside sources or help on this project.
If you discussed this assignment with anyone, please acknowledge them here.
If you used any libraries not mentioned in this module's content, please list them with a brief explanation what you used them for.
If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the generative AI policy.
If no acknowledgments are appropriate, just write none in the file.

Submit "acknowledgments.txt" in Gradescope.

## Part 10: Code

Please submit a Jupyter notebook that can reproduce all your calculations and recreate the previously submitted files.
You do not need to provide code for data collection if you did that by manually.

Submit "project.ipynb" in Gradescope.